"""
Models for the clinical intake flow.

Three tables, all stored in SQLite (db.sqlite3):
  IntakeSession  — one row per patient visit
  Message        — all chat turns (user + agent) for a session
  ClinicalBrief  — the generated CC / HPI / ROS output
"""
import uuid
from django.db import models


class IntakeSession(models.Model):
    """
    Tracks one patient pre-visit intake conversation.

    current_phase drives which questions the agent asks next:
      cc   → Chief Complaint
      hpi  → History of Present Illness  (OLD CARTS framework)
      ros  → Review of Systems
      done → Brief has been generated
    """
    PHASE_CHOICES = [
        ('cc',   'Chief Complaint'),
        ('hpi',  'History of Present Illness'),
        ('ros',  'Review of Systems'),
        ('done', 'Complete'),
    ]

    # Use UUID as PK — safe to expose in URLs, no sequential guessing
    id             = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at     = models.DateTimeField(auto_now_add=True)
    updated_at     = models.DateTimeField(auto_now=True)

    # Which intake phase the agent is currently in
    current_phase  = models.CharField(max_length=10, choices=PHASE_CHOICES, default='cc')

    # Running JSON blob that accumulates structured data as the conversation progresses.
    # Example after HPI is done:
    # {
    #   "cc":  {"complaint": "chest pain", "duration": "3 days"},
    #   "hpi": {"onset": "sudden", "location": "left chest", "severity": "7/10", ...},
    #   "ros": {}
    # }
    collected_data = models.JSONField(default=dict)

    # Flipped to True when the agent decides all phases are complete
    is_complete    = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Session {self.id} | phase={self.current_phase} | complete={self.is_complete}"


class Message(models.Model):
    """
    A single turn in the intake conversation.

    role='user'  → typed text or transcribed voice from the patient
    role='agent' → reply generated by GPT-4o acting as the intake nurse
    """
    ROLE_CHOICES = [
        ('user',  'Patient'),
        ('agent', 'Intake Agent'),
    ]

    session    = models.ForeignKey(
        IntakeSession,
        on_delete=models.CASCADE,
        related_name='messages',
    )
    role       = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content    = models.TextField()
    timestamp  = models.DateTimeField(auto_now_add=True)

    # Set only when the patient used voice input — stores the raw audio for audit
    audio_file = models.FileField(
        upload_to='audio/%Y/%m/%d/',
        null=True,
        blank=True,
    )

    # True when this message's content came from Whisper transcription
    was_transcribed = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return f"[{self.role}] {self.content[:60]}..."


class ClinicalBrief(models.Model):
    """
    The structured clinical brief generated at the end of the intake.
    One-to-one with IntakeSession.

    hpi and ros are stored as JSON so the frontend can render them
    field-by-field without parsing text.
    """
    session          = models.OneToOneField(
        IntakeSession,
        on_delete=models.CASCADE,
        related_name='brief',
    )
    generated_at     = models.DateTimeField(auto_now_add=True)

    # "Chief Complaint" — one sentence
    chief_complaint  = models.TextField()

    # History of Present Illness — OLD CARTS structured
    # Example:
    # {
    #   "onset":       "Sudden onset 3 days ago",
    #   "location":    "Left-sided chest",
    #   "duration":    "Constant over 3 days",
    #   "character":   "Sharp, stabbing",
    #   "aggravating": "Deep breathing, movement",
    #   "alleviating": "Rest, leaning forward",
    #   "radiation":   "No radiation reported",
    #   "timing":      "Continuous",
    #   "severity":    "7/10"
    # }
    hpi              = models.JSONField(default=dict)

    # Review of Systems — per-system findings
    # Example:
    # {
    #   "constitutional":   "Denies fever, chills, or weight loss",
    #   "cardiovascular":   "Reports palpitations; denies syncope",
    #   "respiratory":      "Mild shortness of breath on exertion",
    #   "gastrointestinal": "Denies nausea, vomiting",
    #   "neurological":     "No headache or dizziness",
    #   "musculoskeletal":  "No joint pain",
    #   "skin":             "No rashes"
    # }
    ros              = models.JSONField(default=dict)

    # Full markdown-formatted brief — ready to paste into an EHR note
    raw_text         = models.TextField(blank=True)

    class Meta:
        ordering = ['-generated_at']

    def __str__(self):
        return f"Brief for session {self.session_id} | {self.generated_at:%Y-%m-%d %H:%M}"